# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: AymenSegni
  description: is a special repository
  homepage: https://aymen-segni.com
  topics: all
  private: false
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: false
  is_template: false
  default_branch: main
  delete_branch_on_merge: false
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false

branches:
  - name: main
  - name: metrics
